/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "almacenamiento.h"
#include "GFicheros.c"

bool_t
registeruser_1_svc(char *usuario, int *result,  struct svc_req *rqstp)
{
	bool_t retval;

    *result = registro(usuario);
    retval = TRUE;

	return retval;
}

bool_t
unregisteruser_1_svc(char *usuario, int *result,  struct svc_req *rqstp)
{
	bool_t retval;

    *result = baja(usuario);
    retval = TRUE;

	return retval;
}

bool_t
connectuser_1_svc(char *usuario, int socket, char *port, int *result,  struct svc_req *rqstp)
{
	bool_t retval;

    *result = conectar(usuario, socket, port);
    retval = TRUE;

	return retval;
}

bool_t
disconnectuser_1_svc(char *usuario, int *result,  struct svc_req *rqstp)
{
	bool_t retval;

    *result = desconectar(usuario);
    retval = TRUE;

	return retval;
}

bool_t
publishfile_1_svc(char *descripcion, char *nombre, char *usuario, int *result,  struct svc_req *rqstp)
{
	bool_t retval;

    *result = publicar(descripcion, nombre, usuario);
    retval = TRUE;

	return retval;
}

bool_t
deletefile_1_svc(char *nombre, char *usuario, int *result,  struct svc_req *rqstp)
{
	bool_t retval;

    *result = borrar(nombre, usuario);
    retval = TRUE;

	return retval;
}

int
fileserverrpc_1_freeresult (SVCXPRT *transp, xdrproc_t xdr_result, caddr_t result)
{
	xdr_free (xdr_result, result);

	/*
	 * Insert additional freeing code here, if needed
	 */

	return 1;
}
