/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "almacenamiento.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
registeruser_1(char *usuario, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, registerUser,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &usuario,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
unregisteruser_1(char *usuario, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, unregisterUser,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &usuario,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
connectuser_1(char *usuario, int socket, char *port, int *clnt_res,  CLIENT *clnt)
{
	connectuser_1_argument arg;
	arg.usuario = usuario;
	arg.socket = socket;
	arg.port = port;
	return (clnt_call (clnt, connectUser, (xdrproc_t) xdr_connectuser_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
disconnectuser_1(char *usuario, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, disconnectUser,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &usuario,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
publishfile_1(char *descripcion, char *nombre, char *usuario, int *clnt_res,  CLIENT *clnt)
{
	publishfile_1_argument arg;
	arg.descripcion = descripcion;
	arg.nombre = nombre;
	arg.usuario = usuario;
	return (clnt_call (clnt, publishFile, (xdrproc_t) xdr_publishfile_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
deletefile_1(char *nombre, char *usuario, int *clnt_res,  CLIENT *clnt)
{
	deletefile_1_argument arg;
	arg.nombre = nombre;
	arg.usuario = usuario;
	return (clnt_call (clnt, deleteFile, (xdrproc_t) xdr_deletefile_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}
