/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ALMACENAMIENTO_H_RPCGEN
#define _ALMACENAMIENTO_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


struct connectuser_1_argument {
	char *usuario;
	int socket;
	char *port;
};
typedef struct connectuser_1_argument connectuser_1_argument;

struct publishfile_1_argument {
	char *descripcion;
	char *nombre;
	char *usuario;
};
typedef struct publishfile_1_argument publishfile_1_argument;

struct deletefile_1_argument {
	char *nombre;
	char *usuario;
};
typedef struct deletefile_1_argument deletefile_1_argument;

#define fileserverRPC 99
#define fileServer 1

#if defined(__STDC__) || defined(__cplusplus)
#define registerUser 1
extern  enum clnt_stat registeruser_1(char *, int *, CLIENT *);
extern  bool_t registeruser_1_svc(char *, int *, struct svc_req *);
#define unregisterUser 2
extern  enum clnt_stat unregisteruser_1(char *, int *, CLIENT *);
extern  bool_t unregisteruser_1_svc(char *, int *, struct svc_req *);
#define connectUser 3
extern  enum clnt_stat connectuser_1(char *, int , char *, int *, CLIENT *);
extern  bool_t connectuser_1_svc(char *, int , char *, int *, struct svc_req *);
#define disconnectUser 4
extern  enum clnt_stat disconnectuser_1(char *, int *, CLIENT *);
extern  bool_t disconnectuser_1_svc(char *, int *, struct svc_req *);
#define publishFile 5
extern  enum clnt_stat publishfile_1(char *, char *, char *, int *, CLIENT *);
extern  bool_t publishfile_1_svc(char *, char *, char *, int *, struct svc_req *);
#define deleteFile 6
extern  enum clnt_stat deletefile_1(char *, char *, int *, CLIENT *);
extern  bool_t deletefile_1_svc(char *, char *, int *, struct svc_req *);
extern int fileserverrpc_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define registerUser 1
extern  enum clnt_stat registeruser_1();
extern  bool_t registeruser_1_svc();
#define unregisterUser 2
extern  enum clnt_stat unregisteruser_1();
extern  bool_t unregisteruser_1_svc();
#define connectUser 3
extern  enum clnt_stat connectuser_1();
extern  bool_t connectuser_1_svc();
#define disconnectUser 4
extern  enum clnt_stat disconnectuser_1();
extern  bool_t disconnectuser_1_svc();
#define publishFile 5
extern  enum clnt_stat publishfile_1();
extern  bool_t publishfile_1_svc();
#define deleteFile 6
extern  enum clnt_stat deletefile_1();
extern  bool_t deletefile_1_svc();
extern int fileserverrpc_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_connectuser_1_argument (XDR *, connectuser_1_argument*);
extern  bool_t xdr_publishfile_1_argument (XDR *, publishfile_1_argument*);
extern  bool_t xdr_deletefile_1_argument (XDR *, deletefile_1_argument*);

#else /* K&R C */
extern bool_t xdr_connectuser_1_argument ();
extern bool_t xdr_publishfile_1_argument ();
extern bool_t xdr_deletefile_1_argument ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ALMACENAMIENTO_H_RPCGEN */
