/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "almacenamiento.h"

bool_t
xdr_connectuser_1_argument (XDR *xdrs, connectuser_1_argument *objp)
{
	 if (!xdr_string (xdrs, &objp->usuario, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->socket))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->port, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_publishfile_1_argument (XDR *xdrs, publishfile_1_argument *objp)
{
	 if (!xdr_string (xdrs, &objp->descripcion, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->nombre, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->usuario, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_deletefile_1_argument (XDR *xdrs, deletefile_1_argument *objp)
{
	 if (!xdr_string (xdrs, &objp->nombre, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->usuario, ~0))
		 return FALSE;
	return TRUE;
}
