/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "almacenamiento.h"


void
fileserverrpc_1(char *host)
{
	CLIENT *clnt;
	enum clnt_stat retval_1;
	int result_1;
	char *registeruser_1_usuario;
	enum clnt_stat retval_2;
	int result_2;
	char *unregisteruser_1_usuario;
	enum clnt_stat retval_3;
	int result_3;
	char *connectuser_1_usuario;
	int connectuser_1_socket;
	char *connectuser_1_port;
	enum clnt_stat retval_4;
	int result_4;
	char *disconnectuser_1_usuario;
	enum clnt_stat retval_5;
	int result_5;
	char *publishfile_1_descripcion;
	char *publishfile_1_nombre;
	char *publishfile_1_usuario;
	enum clnt_stat retval_6;
	int result_6;
	char *deletefile_1_nombre;
	char *deletefile_1_usuario;

#ifndef	DEBUG
	clnt = clnt_create (host, fileserverRPC, fileServer, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	retval_1 = registeruser_1(registeruser_1_usuario, &result_1, clnt);
	if (retval_1 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_2 = unregisteruser_1(unregisteruser_1_usuario, &result_2, clnt);
	if (retval_2 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_3 = connectuser_1(connectuser_1_usuario, connectuser_1_socket, connectuser_1_port, &result_3, clnt);
	if (retval_3 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_4 = disconnectuser_1(disconnectuser_1_usuario, &result_4, clnt);
	if (retval_4 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_5 = publishfile_1(publishfile_1_descripcion, publishfile_1_nombre, publishfile_1_usuario, &result_5, clnt);
	if (retval_5 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_6 = deletefile_1(deletefile_1_nombre, deletefile_1_usuario, &result_6, clnt);
	if (retval_6 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	fileserverrpc_1 (host);
exit (0);
}
