
package Mayus;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MayusService", targetNamespace = "http://Mayus/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MayusService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "toUpper", targetNamespace = "http://Mayus/", className = "Mayus.ToUpper")
    @ResponseWrapper(localName = "toUpperResponse", targetNamespace = "http://Mayus/", className = "Mayus.ToUpperResponse")
    @Action(input = "http://Mayus/MayusService/toUpperRequest", output = "http://Mayus/MayusService/toUpperResponse")
    public String toUpper(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
