
package Mayus;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MayusServiceService", targetNamespace = "http://Mayus/", wsdlLocation = "file:/run/media/xan/Datos/BACKUPS/Linux/xan/Documentos/Distribueno/distributed/Parte%203/MayusService.wsdl")
public class MayusServiceService
    extends Service
{

    private final static URL MAYUSSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException MAYUSSERVICESERVICE_EXCEPTION;
    private final static QName MAYUSSERVICESERVICE_QNAME = new QName("http://Mayus/", "MayusServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/run/media/xan/Datos/BACKUPS/Linux/xan/Documentos/Distribueno/distributed/Parte%203/MayusService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MAYUSSERVICESERVICE_WSDL_LOCATION = url;
        MAYUSSERVICESERVICE_EXCEPTION = e;
    }

    public MayusServiceService() {
        super(__getWsdlLocation(), MAYUSSERVICESERVICE_QNAME);
    }

    public MayusServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MAYUSSERVICESERVICE_QNAME, features);
    }

    public MayusServiceService(URL wsdlLocation) {
        super(wsdlLocation, MAYUSSERVICESERVICE_QNAME);
    }

    public MayusServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MAYUSSERVICESERVICE_QNAME, features);
    }

    public MayusServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MayusServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MayusService
     */
    @WebEndpoint(name = "MayusServicePort")
    public MayusService getMayusServicePort() {
        return super.getPort(new QName("http://Mayus/", "MayusServicePort"), MayusService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MayusService
     */
    @WebEndpoint(name = "MayusServicePort")
    public MayusService getMayusServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Mayus/", "MayusServicePort"), MayusService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MAYUSSERVICESERVICE_EXCEPTION!= null) {
            throw MAYUSSERVICESERVICE_EXCEPTION;
        }
        return MAYUSSERVICESERVICE_WSDL_LOCATION;
    }

}
